### ISSUE TITLE
Debugger can't seem to find file if not using absolute paths

### ISSUE THREAD

**Issue by mundusnine** [sssooonnnggg/luau-debugger#3]
When using the command in the terminal of my vscode workspace:
`./Deployment/MyExecutable 58000 ./Deployment/data/main.lua`

I then attach with the vscode launch.json and I get this : 
![image](https://github.com/user-attachments/assets/c7f16405-96f1-41ef-8a31-99026ea9ee57)

If I set an absolute path using:
```json
//tasks.json
{
            "label": "Build and run game",
            "type": "shell",
            "command": "${workspaceRoot}/Deployment/MyExecutable",
            "args": [
                "58000",
                "${workspaceRoot}/Deployment/data/main.lua"
            ],
            "dependsOn":[
                "Build game"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
```
I get to view the file source without issue.

I am running on Linux(SteamOS Btw).

**Comment by sssooonnnggg** [comment]
Nice catch, it has been fixed.
