### ISSUE TITLE
Can't find nlohmann_json_serializer.h

### ISSUE THREAD

**Issue by mikejohnstn** [sssooonnnggg/luau-debugger#4]
Hi there, I'm excited to try this. Thanks for making it!

I'm trying to integrate it into my own project. My only problem so far is I can't find `<nlohmann_json_serializer.h>`. Is that just a missing dependency / wrapper?

I could try using https://github.com/nlohmann/json myself, but I'm hoping this is a quick fix or maybe a simple misunderstanding on my part.

**Comment by sssooonnnggg** [comment]
Hi,  this file is a part of  `cppdap` which is a dependency of the debugger, you can pull `cppdap` as dependency and in cppdap repo root, run `git submodule update --init`. Then pass `-DCPPDAP_ROOT=<your cppdap root> -DLUAU_ROOT=<your luau root>` to cmake. 
https://github.com/google/cppdap/blob/main/src/nlohmann_json_serializer.h
If you encounter any problems, please feel free to ask.😊

**Comment by sssooonnnggg** [comment]
https://github.com/sssooonnnggg/luau-debugger/blob/master/.github/workflows/publish.yml
These codes can be used as a compilation example (Windows or Ubuntu)

**Comment by mikejohnstn** [comment]
I see, thanks! I'm not using cmake and I somehow didn't see that `nlohmann_json.serializer.h` is part of `cppdap`.

It's building now and I just need to solve a couple problems that are probably also my fault. :)
